/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package modelos_juego_sin_nombre;

import java.io.Serializable;
import java.util.ArrayList;

public class EnvioLLegadaPreguntas implements Serializable{
    private ArrayList<Pregunta> preguntas = new ArrayList<>();
}
