/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGraficaProfesor;

import admincenterprofesor.AdminCenterProfesor;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelos_juego_sin_nombre.Batalla;
import modelos_juego_sin_nombre.Usuario;

/**
 *
 * @author aleja
 */
public class AdminJuego extends javax.swing.JFrame {

    //variables
    private boolean prueba = true;
    private AdminCenterProfesor admProfesor;
    private ArrayList<Batalla> batallas;
    private Usuario jugador1;
    private Usuario jugador2;
    ArrayList<Usuario> jugadores;
    ArrayList<Usuario> jugadoresDisponibles;
    ArrayList<Usuario> jugadoresEnBatalla;
    String[] listaJugadoresDisponiblesArr = new String[20];
    String[] listaJugadoresArr = new String[20];
    /**
     * Creates new form AdminJuego
     */
    public AdminJuego() {
        admProfesor = new AdminCenterProfesor();
        batallas = new ArrayList<>();
        jugadoresEnBatalla =  new ArrayList<>();
        jugadores = new ArrayList<>();
        jugadoresDisponibles =  new ArrayList<>();
        initComponents();
        llenarListaGraficaJugadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtJugador1 = new java.awt.TextField();
        txtJugador2 = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSeleccionarJugador = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        gListTxtJugadores = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        gListTxtJugadoresDisp = new javax.swing.JList<>();
        btnActualizarJugadoresDisponibles = new java.awt.Button();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnCrearBatalla = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        gListTxtJugadoresDisp1 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Jugador 2");

        txtJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJugador1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("JugadoresConectados");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Preguntas");

        btnSeleccionarJugador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSeleccionarJugador.setLabel("Seleccionar");
        btnSeleccionarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarJugadorActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(gListTxtJugadores);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("JugadoresDisponibles");

        jScrollPane2.setViewportView(gListTxtJugadoresDisp);

        btnActualizarJugadoresDisponibles.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizarJugadoresDisponibles.setLabel("Actualizar");
        btnActualizarJugadoresDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarJugadoresDisponiblesActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        btnCrearBatalla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCrearBatalla.setLabel("Crear Batalla");
        btnCrearBatalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearBatallaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Jugador 1");

        jScrollPane4.setViewportView(gListTxtJugadoresDisp1);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Batallas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(btnActualizarJugadoresDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(btnSeleccionarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(277, 277, 277))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearBatalla, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnActualizarJugadoresDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addContainerGap(281, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSeleccionarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrearBatalla, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJugador1ActionPerformed
        
    }//GEN-LAST:event_txtJugador1ActionPerformed

    private void btnSeleccionarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarJugadorActionPerformed
        try
        {
            int indexJugador = gListTxtJugadoresDisp.getSelectedIndex();
            String nombre = jugadores.get(indexJugador).getUserName();
            if(txtJugador1.getText().equals("") && jugadoresDisponibles.stream().anyMatch(c -> c.getUserName().equals(nombre))){
                jugador1 = new Usuario();
                jugador1.setUserName(jugadores.get(indexJugador).getUserName());
                jugador1.setIp(jugadores.get(indexJugador).getIp());
                jugador1.setAvatar(jugadores.get(indexJugador).getAvatar());
                jugadoresDisponibles.removeIf(c -> c.getIp()== jugador1.getIp());
                listaJugadoresDisponiblesArr[indexJugador] = null;
                jugadoresEnBatalla.add(jugador1);
                txtJugador1.setText(jugador1.getUserName());
            }  
            else if(txtJugador2.getText().equals("") && jugadoresDisponibles.stream().anyMatch(c -> c.getUserName().equals(nombre))){
                jugador2 = new Usuario();
                jugador2.setUserName(jugadores.get(indexJugador).getUserName());
                jugador2.setIp(jugadores.get(indexJugador).getIp());
                jugador2.setAvatar(jugadores.get(indexJugador).getAvatar());
                jugadoresDisponibles.removeIf(c -> c.getIp()== jugador2.getIp());
                listaJugadoresDisponiblesArr[indexJugador] = null;
                jugadoresEnBatalla.add(jugador2);
                txtJugador2.setText(jugador2.getUserName());
            }  
        }catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, "Ingresa un jugador valido", "Error al seleccionar jugador", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_btnSeleccionarJugadorActionPerformed

    
    private void btnActualizarJugadoresDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarJugadoresDisponiblesActionPerformed
        gListTxtJugadores.removeAll();
        gListTxtJugadoresDisp.removeAll();
        jugadores = new ArrayList<>();
        jugadoresDisponibles =  new ArrayList<>();
        llenarListaGraficaJugadores();
    }//GEN-LAST:event_btnActualizarJugadoresDisponiblesActionPerformed

    private void btnCrearBatallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearBatallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearBatallaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminJuego().setVisible(true);
            }
        });
    }
    
    private void llenarListaGraficaJugadores()
    {
        
        
        gListTxtJugadores.setListData(listaJugadoresArr);
        gListTxtJugadoresDisp.setListData(listaJugadoresDisponiblesArr);
        int contador = 0;
        if(prueba)
        {
            Usuario u1= new Usuario("Alejandro", "jugador1", "192.668.1.45");
            Usuario u2= new Usuario("Sofia", "jugador2", "192.668.1.65");
            Usuario u3= new Usuario("Sonia", "jugador3", "192.668.1.39");
            Usuario u4= new Usuario("Juan", "jugador4", "192.668.1.3");
            jugadores.add(u1);
            jugadores.add(u2);
            jugadores.add(u3);
            jugadores.add(u4);
            jugadoresDisponibles.addAll(jugadores);
            for(Usuario usuario : jugadores)
            {
                listaJugadoresArr[contador] = usuario.getUserName();
                listaJugadoresDisponiblesArr[contador] = usuario.getUserName();
                contador++;
                if(contador == jugadores.size()){
                    for(int i = contador; i<listaJugadoresArr.length;i++){
                        listaJugadoresArr[i] = null;
                        listaJugadoresDisponiblesArr[i] = null;
                    }
                }
            }
        }
        else
        {
            jugadores = admProfesor.getJugadoresConectados();
            jugadoresDisponibles.addAll(jugadores);
            for(Usuario usuario : jugadores)
            {
                listaJugadoresArr[contador] = usuario.getUserName();
                listaJugadoresDisponiblesArr[contador] = usuario.getUserName();
                contador++;
            }
        
        
        }

    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnActualizarJugadoresDisponibles;
    private java.awt.Button btnCrearBatalla;
    private java.awt.Button btnSeleccionarJugador;
    private javax.swing.JList<String> gListTxtJugadores;
    private javax.swing.JList<String> gListTxtJugadoresDisp;
    private javax.swing.JList<String> gListTxtJugadoresDisp1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.TextField txtJugador1;
    private java.awt.TextField txtJugador2;
    // End of variables declaration//GEN-END:variables
}
